server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-jolly-lab-abme4tiv-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bC4KoPql7uWG
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: show SQL queries in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=wPRm5TI2eJ+FnVuAdZkaT04+hdQuz6mcDhSYT8M92Lgshabfjdsbf

spring.profiles.active=default

# gRPC server config
grpc.server.address=0.0.0.0
grpc.server.port=9099
grpc.server.maxMessageSize=10485760
